apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: demo-app
  template:
    metadata:
      labels:
        name: demo-app
    spec:
      containers:
        - name: demo-app
          image: abhimanyurcr.azurecr.io/sample-project/sample-project
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: k8s-secret
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  type: NodePort
  selector:
    name: demo-app
  ports:
    - port: 8081
      targetPort: 8081