'on':
  pull_request:
    branches:
      - master
      - develop
jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scan-ref: .
          trivy-config: trivy.yaml
          format: template
          template: "@trivy/github-markdown.tpl"
          output: trivy.md
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          exit-code: 1
    - run: cat trivy.md >> $GITHUB_STEP_SUMMARY
        if: always()
      - name: Echo
        run: |
            echo ${{ github.step_summary }}
