'on':
  pull_request:
    branches:
      - master
      - develop
jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scan-ref: .
          trivy-config: trivy.yaml
          output: trivy-output.txt

      - name: Upload Trivy scan report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-report
          path: trivy-output.txt

      - name: Download Trivy scan report
        uses: actions/download-artifact@v3
        with:
          name: trivy-scan-report
          path: ./artifact-download

      - name: Echo Trivy scan report contents
        run: cat ./artifact-download/trivy-output.txt
