name: Security Scan and PR Comment
on:
  pull_request:
    branches:
      - master
      - development

jobs:
  trivy-scan:
    name: Trivy Filesystem Scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy on project filesystem
        id: trivy_scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          input: '.'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Capture Trivy Scan Output
        id: capture_trivy_output
        run: echo "TRIVY_SCAN_RESULTS<<EOF" >> $GITHUB_ENV && cat ${{ steps.trivy_scan.outputs.results }} >> $GITHUB_ENV && echo "EOF" >> $GITHUB_ENV

      - name: Post Trivy Scan Results to PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Trivy Scan Results:**

            ```plaintext
            ${{ env.TRIVY_SCAN_RESULTS }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
