'on':
  pull_request:
    branches:
      - master
      - develop
jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scan-ref: .
          trivy-config: trivy.yaml
          output: trivy-output.txt
   
      - name: Check if Trivy output file exists
        run: |
          if [ ! -f trivy-output.txt ]; then
            echo "Error: trivy-output.txt not found!"
            exit 1
          else
            echo "trivy-output.txt found, proceeding with upload."
          fi
